### ISSUE TITLE
Add option to allow mutable install hooks for local AEM SDK development

### ISSUE THREAD

**Issue by royteeuwen** [Netcentric/aem-cloud-validator#31]
When developing with the AEM SDK, a common approach is to use InstallHook's to trigger actions when a mutable content package is installed. This is for example done by the Netcentric accesscontroltool. To make it possible to leverage this capability, there should be an option to disable the error for install hooks in mutable content for local development

**Comment by royteeuwen** [comment]
is resolved by #30

**Comment by kwin** [comment]
@royteeuwen Thanks for the PR. Do you know if install hooks in mutable packages work meanwhile in Cloud Manager as well? Adobe recently updated FileVault to a newer version so potentially they have fixed this...

**Comment by kwin** [comment]
I just checked the OSGi configuration of an AEM Cloud instance version `2023.4.11873.20230421T153841Z` and it still doesn't contain the necessary OSGi config for PID `org.apache.jackrabbit.vault.packaging.impl.PackagingImpl` to grant the `sling-distribution-importer` the rights to execute install hooks, unfortunately.

**Comment by royteeuwen** [comment]
@kwin ok, good to know! Nowadays we just use the startuphooks for cloud, dont know if it covers all cases though.

what do you recommend for this PR? I can update the readme with the osgi conf you show, or we can create support cases to request the osgi conf ;)?

**Comment by kwin** [comment]
I will take care of both :-) and go ahead with your PR as is first.
